### ISSUE TITLE
upload it to F-droid

### ISSUE THREAD

**Issue by alezzacreative** [xiprox/NamazVakitleri#2]
hi because of nature of your app as an open source project i encourage you to make it available on the F-droid app store were only open source apps that respect the privacy of the users are
there is a lack of arabic/ islamic apps there
may Allah protect you
the official link : https://f-droid.org/en/
the submission process : https://gitlab.com/fdroid/rfp/

**Comment by xiprox** [comment]
Hi. Did you even spend a minute looking at the repository? It's been 5 years since the last commit. There's clearly no plans to do further work.

If you are interested, please feel free to make a fork and publish the app yourself.
